spring:
  application:
    name: rental-alipay
  datasource:
    url: jdbc:mysql://localhost:3306/healer_rental?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
    fetch-registry: true
    register-with-eureka: true